export enum RoutePath {
  Home = "MedTutor",
  ABOUTHPAT = "hpat",
  HPATDATES = "hpat-dates",
  HPATCHANGES = "hpat-changes",
  GROUPPREP = "group-prep",
  WEEKPREP = "week-prep",
  LEAVINGCERT = "leaving-cert",
  JUNIORCERT = "junior-cert",
  UCATTUTOR = "ucat-tutoring",
  UCATCOURSES = "ucat-courses",
  PERSONALGUIDANCE = "personal-guidance",
  PERSONALREVIEW = "personal-review",
  PERSONALFAQ = "personal-faqs",
  UCASEXTRA="ucas-extra",
  APPLICATIONSTRATEGY="application-strategy",
  MMI="mmi",
  OXBRIDGE="oxbridge",
  MEDICINALPANEL="medicinal-panel",
    PANEL="panel",
}
