export enum RoutePath {
  Home = "MedTutor",
  ABOUTHPAT = "ABOUT-HPAT",
  HPATDATES = "HPAT-DATES",
  HPATCHANGES = "HPAT-CHANGES",
  GROUPPREP = "GROUP-PREP",
  WEEKPREP = "WEEK-PREP",
  LEAVINGCERT = "LEAVING-CERT",
}
